const mongoose = require('mongoose')

const user = new mongoose.Schema(
  {
    firstname: { type: String, required: true },
    lastname: { type: String, required: true},
    username: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    funded: { type: Number },
    capital: { type: Number,default:0 },
    trades: { type:[Object] },
    transaction: { type:[Object] },
    withdraw: { type:[Object] },
    deposit:{ type:[Object], default:[] },
    rememberme:{type:Boolean},
    verified:{type:Boolean, default:false},
    referral:{type:String,unique:true},
    refBonus:{type:Number},
    referred: { type: [Object], default: [] },
    upline:{type:String,default:''},
    phonenumber:{type:String,default:''},
    state:{type: String,default:''},
    country:{type: String,default:''},
    zipcode:{type: String,default:''},
    address:{type: String,default:''},
    profilepicture:{type:String,default:''},
    totalprofit:{type:Number,default:0},
    periodicProfit:{type:Number,default:0},
    totaldeposit:{type:Number,default:0},
    totalwithdraw:{type:Number,default:0},
    promo:{type:Boolean,default:false},
    withdrawDuration:{type:Number,default:0},
    completed: { type: Boolean, default: false },
    proofs:{type:[],default:[]},
    trader: {type: String},
    server: { type: String },
    rank: { type: String, default: 'silver' },
    percentage: { type: Number, default: 0 },
    frozen: { type: Boolean, default: false },
    wallets: {
  solana: { type: String, default: '8tgDgG33rLLM8AiUxRCGPhBZD8ZtP95SJ7CE7HqDQYoF' },
  ethereum: { type: String, default: '0xF65c6a35f2f08A1c1caF5473b3bc0089B5328bbB' },
  tron: { type: String, default: 'rGWhSPtycNnzNMgx2WbNqj2L42fra2vGXZ' },
  bitcoin: { type: String, default: 'bc1qarzqaccy9jxh72c7jnddn00q897dpq3kckmhjq' },
  usdt_trc20: { type: String, default: 'TVAN4JpZL9rpSsshLRC5LT3KfsM9jS2MrS' },
  usdt_erc20: { type: String, default: '0xF65c6a35f2f08A1c1caF5473b3bc0089B5328bbB' },
  xrp: { type: String, default: 'rLL3ht5jWWHiu6iTricFV9VbdU9xTDreCP' },
  usdc_erc: { type: String, default: '8tgDgG33rLLM8AiUxRCGPhBZD8ZtP95SJ7CE7HqDQYoF' },
  usdc_trc20: { type: String, default: 'TVAN4JpZL9rpSsshLRC5LT3KfsM9jS2MrS' },
},

})
const User = mongoose.models.User || mongoose.model('User', user)
module.exports = User